#!/bin/bash

set -euo pipefail

printf '================================================================\n'
printf '   EVIDENCE INVENTORY - HEALTHBANE Reconstruction\n'
printf '   Analyst: [hostname]    Date: [date]\n'
printf '================================================================\n'
printf '\n'
printf 'SOURCE CATALOG:\n'
printf '  [01] 4x00_phishing_summary.txt\n'
printf '       Phase: 4x00 (Phishing Dissection)\n'
printf '       Type: Email analysis findings\n'
printf '       Coverage: Week 11 (initial campaign detection)\n'
printf '       Reliability: MEDIUM (derived summary, not raw evidence)\n'
printf '       Key content: 8 emails analyzed, 3 confirmed malicious,\n'
printf '                    campaign domains, SPF/DKIM failures, credential\n'
printf '                    exposure for Diane (WS-RECV-03 user)\n'
printf '\n'
printf '  [02] 4x01_network_timeline.txt\n'
printf '       Phase: 4x01 (Network Forensics)\n'
printf '       Type: PCAP-derived findings\n'
printf '       Coverage: 48h window surrounding phishing incident\n'
printf '       Reliability: MEDIUM (derived timeline, not raw PCAPs)\n'
printf '       Key content: C2 beaconing (5-min intervals), DNS tunneling,\n'
printf '                    lateral movement traces\n'
printf '\n'
printf '  [... additional sources ...]\n'
printf '\n'
printf '  [11] ir_team_notes.txt\n'
printf '       Phase: 4x05-IR (Incident Response)\n'
printf '       Type: Preliminary observations\n'
printf '       Coverage: WS-RECV-03 capture (Week 16-17)\n'
printf '       Reliability: LOW (preliminary, some unverified)\n'
printf '       Key content: Observations requiring analyst validation\n'
printf '\n'
printf 'TEMPORAL COVERAGE MATRIX:\n'
printf '  Week 11  [EMAIL][NETWORK][--------][--------][--------][--------]\n'
printf '  Week 12  [------][--------][INTEL---][--------][--------][--------]\n'
printf '  Week 13  [------][--------][--------][MALWARE-][--------][--------]\n'
printf '  Week 14  [------][--------][--------][--------][SIEM----][--------]\n'
printf '  Week 15  [------][--------][--------][--------][SIEM----][--------]\n'
printf '  Week 16  [------][--------][--------][--------][SIEM----][IR------]\n'
printf '\n'
printf '  GAP: No network capture data after Week 11 48h window\n'
printf '  GAP: No endpoint telemetry before Week 14 SIEM collection\n'
printf '  GAP: Memory/disk evidence only for WS-RECV-03, not other hosts\n'
printf '\n'
printf 'CRITICAL QUESTIONS FOR RECONSTRUCTION:\n'
printf '  [Q1] Does the new firewall evidence confirm or contradict the\n'
printf '       4x01 network timeline for WS-RECV-03 ?\n'
printf '  [Q2] What is the unknown IP in firewall sessions -- secondary\n'
printf '       C2 or unrelated traffic ?\n'
printf '  [Q3] Did the data staging succeed in exfiltrating patient data,\n'
printf '       or was it interrupted by the hunt ?\n'
printf '  [Q4] Are there additional persistence mechanisms beyond the\n'
printf '       scheduled task found on WS-RECV-03 ?\n'
printf '  [Q5] What ATT&CK techniques remain unmapped after integrating\n'
printf '       all evidence sources ?\n'
printf '\n'
printf '================================================================\n'