#!/bin/bash

set -euo pipefail

printf '================================================================\n'
printf '   DISK FORENSICS ANALYSIS - WS-RECV-03\n'
printf '   Source: ir_evidence/disk_forensics_report.txt\n'
printf '================================================================\n'
printf '\n'
printf 'RECOVERED DELETED FILES:\n'
printf '  File                      Orig Path            Deleted     Size\n'
printf '  staging_export_001.zip    C:\Users\Public\Tmp\  Feb 10     14.2 MB\n'
printf '  staging_export_002.zip    C:\Users\Public\Tmp\  Feb 11     11.8 MB\n'
printf '  query_results.csv         C:\Users\Public\Tmp\  Feb 10     8.4 MB\n'
printf '\n'
printf '  ANALYSIS: Three files recovered from C:\Users\Public\Tmp\.\n'
printf '  Naming pattern suggests structured data export. CSV file size\n'
printf '  consistent with database query results. ZIP files created AFTER\n'
printf '  CSV, suggesting compression for exfiltration staging.\n'
printf '  ATT&CK: T1074.001 Local Data Staging, T1560.001 Archive via Utility\n'
printf '  CRITICAL: Staging occurred Feb 10-11, hunt detected activity Feb 12.\n'
printf '  The attacker was preparing to exfiltrate when the hunt interrupted.\n'
printf '\n'
printf 'PREFETCH ANALYSIS:\n'
printf '  Program              First Exec    Last Exec     Expected?\n'
printf '  PSEXEC.EXE           Feb 05 02:13  Feb 12 01:44  NO (records WS)\n'
printf '  POWERSHELL.EXE       Jan 15 09:00  Feb 12 02:01  PARTIAL (normal use\n'
printf '                                                     but off-hours suspect)\n'
printf '  [STAGING_TOOL]       Feb 09 23:41  Feb 11 01:15  NO (data collection)\n'
printf '  CMD.EXE              Jan 02 10:00  Feb 12 01:55  YES (standard)\n'
printf '\n'
printf 'SCHEDULED TASK (confirms memory analysis):\n'
printf '  Task XML: HealthSync Update Service\n'
printf '  Trigger: DailyTrigger, StartBoundary=02:00:00\n'
printf '  Action: powershell.exe -ExecutionPolicy Bypass -enc [base64]\n'
printf '  Registration: 2024-02-06T01:47:33\n'
printf '  -> CONFIRMED: matches memory artifact from T1\n'
printf '\n'
printf 'REGISTRY PERSISTENCE:\n'
printf '  HKLM\...\Run: No suspicious entries found\n'
printf '  HKCU\...\Run: No suspicious entries found\n'
printf '  -> Attacker relied on scheduled task, not registry run keys\n'
printf '\n'
printf 'ANTI-FORENSICS INDICATORS:\n'
printf '  [*] Windows Security Event Log: gap from Feb 08 03:00 to 03:12\n'
printf '      -> 12-minute gap consistent with selective event deletion\n'
printf '      ATT&CK: T1070.001 Clear Windows Event Logs\n'
printf '  [*] $MFT timestamps for C:\Users\Public\Tmp\: standard ordering\n'
printf '      -> No timestamp manipulation detected\n'
printf '\n'
printf 'NTFS TIMELINE (attack window Feb 04-12):\n'
printf '  Feb 04 01:23  credential_tool created in C:\Windows\Temp\\n'
printf '  Feb 06 01:47  Scheduled task XML written\n'
printf '  Feb 08 02:55  [Evidence of lateral movement tool usage]\n'
printf '  Feb 09 23:41  First staging tool execution\n'
printf '  Feb 10 14:22  query_results.csv created\n'
printf '  Feb 10 15:07  staging_export_001.zip created\n'
printf '  Feb 11 01:08  staging_export_002.zip created\n'
printf '  Feb 11 01:22  Deleted files: query_results.csv, staging zips\n'
printf '  Feb 12 01:44  Last PsExec execution (detected by 4x04 hunt)\n'
printf '\n'
printf 'SUMMARY:\n'
printf '  New ATT&CK techniques: T1074.001, T1560.001, T1070.001\n'
printf '  Evidence confirms data staging for exfiltration\n'
printf '  Staging interrupted before confirmed data exfiltration\n'
printf '  Anti-forensics: partial log deletion (12-min gap)\n'
printf '\n'
printf '================================================================\n'