#!/bin/bash

set -euo pipefail

printf '================================================================\n'
printf '   CROSS-EVIDENCE CORRELATION MATRIX\n'
printf '   Sources: 4x00 through 4x05-IR (11 evidence files)\n'
printf '================================================================\n'
printf '\n'
printf 'IOC CORRELATION:\n'
printf '  IOC                    4x00  4x01  4x02  4x03  4x04  IR    Status\n'
printf '  [phish_domain]         YES   ---   YES   ---   ---   ---   CONVERGED\n'
printf '  185.220.101.45                ---   YES   YES   YES   ---   YES   CONVERGED\n'
printf '  203.0.113.47           ---   ---   ---   ---   ---   YES   SINGLE-SOURCE\n'
printf '  svchost_update.exe     ---   ---   YES   YES   ---   YES   CONVERGED\n'
printf '  svc_healthsync         ---   ---   ---   ---   YES   YES   CONVERGED\n'
printf '  [staging_tool]         ---   ---   ---   ---   ---   YES   SINGLE-SOURCE\n'
printf '  [...]\n'
printf '\n'
printf '  Summary: [N] CONVERGED, [N] SINGLE-SOURCE, [N] CONFLICTED\n'
printf '  New IOCs from IR: [N]\n'
printf '\n'
printf 'TIMELINE CORRELATION:\n'
printf '  Event                  Sources              Confidence  Notes\n'
printf '  Phishing delivery      4x00                 HIGH        Primary evidence\n'
printf '  Credential theft       4x00,4x01            CONVERGED   Timestamps match\n'
printf '  C2 establishment       4x01,IR-FW           CONVERGED   4s clock skew\n'
printf '  Malware deployment     4x03,IR-MEM          CONVERGED   Process confirmed\n'
printf '  Persistence install    IR-MEM,IR-DISK       CONVERGED   Feb 06 01:47\n'
printf '  Lateral mvmt start     4x04,IR-FW           CONVERGED   Feb 05\n'
printf '  Data staging           IR-DISK              SINGLE      Feb 10-11\n'
printf '  [...]\n'
printf '\n'
printf '  CONTRADICTION RESOLVED:\n'
printf '  -> 4x01 network timeline shows C2 beacon start at [time]\n'
printf '  -> IR firewall shows first C2 session at [time - delta]\n'
printf '  -> Resolution: Firewall records TCP SYN (connection start),\n'
printf '     PCAP captured mid-session. [delta]s difference is consistent\n'
printf '     with normal collection point variance. Firewall timestamp\n'
printf '     adopted as authoritative for connection initiation.\n'
printf '\n'
printf 'TECHNIQUE CORRELATION:\n'
printf '  Technique              4x02    4x04    IR      Update\n'
printf '  T1566.001 Phishing     CONF    ---     ---     No change\n'
printf '  T1566.002 Spearphish   CONF    ---     ---     No change\n'
printf '  T1583.001 Acquire Dom  CONF    ---     ---     No change\n'
printf '  T1078 Valid Accounts   CONF    ---     ---     No change\n'
printf '  T1071.001 Web Proto    CONF    ---     CONF    Confidence +\n'
printf '  T1573.001 Encrypted    CONF    ---     CONF    Confidence +\n'
printf '  T1071.004 DNS          CONF    ---     CONF    Confidence +\n'
printf '  T1105 Tool Transfer    CONF    ---     CONF    Confidence +\n'
printf '  T1204.002 User Exec    INFER   ---     ---     No change\n'
printf '  T1059.005 VBA          INFER   ---     ---     No change\n'
printf '  T1059.001 PowerShell   INFER   ---     CONF    UPGRADED\n'
printf '  T1547.001 Run Keys     INFER   ---     CONF    UPGRADED\n'
printf '  T1027 Obfuscation      INFER   ---     CONF    UPGRADED\n'
printf '  T1140 Deobfuscation    ---     ---     CONF    NEW\n'
printf '  T1027.010 Cmd Obfusc.  ---     ---     CONF    NEW\n'
printf '  T1041 Exfil over C2    INFER   ---     CONF    UPGRADED\n'
printf '  T1048.003 DNS Exfil    INFER   ---     ---     No change\n'
printf '  T1005 Local Collection ---     ---     CONF    NEW\n'
printf '  T1003.001 LSASS        ---     CONF    CONF    CONFIRMED\n'
printf '  T1021.002 PsExec       ---     CONF    CONF    CONFIRMED\n'
printf '  T1021.006 PSRemoting   ---     CONF    CONF    CONFIRMED\n'
printf '  T1047 WMI              ---     CONF    CONF    CONFIRMED\n'
printf '  T1078.002 Domain Acct  ---     CONF    CONF    CONFIRMED\n'
printf '  T1550.002 Pass-the-Hash ---     CONF    CONF    CONFIRMED\n'
printf '  T1112 Registry Mod.    ---     ---     CONF    NEW\n'
printf '  T1053.005 Sched Task   ---     ---     CONF    NEW\n'
printf '  T1074.001 Data Staging ---     ---     CONF    NEW\n'
printf '  T1560.001 Archive      ---     ---     CONF    NEW\n'
printf '  T1070.001 Log Clear    ---     ---     PROB    NEW\n'
printf '  [...]\n'
printf '\n'
printf '  Techniques UPGRADED from INFERRED to CONFIRMED: 4\n'
printf '  Techniques newly identified from IR evidence: 8\n'
printf '  Techniques CORRECTED (4x02 inference was wrong): 0\n'
printf '\n'
printf '================================================================\n'