#!/usr/bin/env bash
# script to manage the script called manage_my_process

if [ "$#" -ne 1 ]; then
	echo "Usage: manage_my_process {start|stop|restart}"
	exit
fi

if [ "$1" == "start" ]; then
	bash manage_my_process &
	echo "$!" > /tmp/my_process.pid
	echo "manage_my_process started"
elif [ "$1" == "stop" ]; then
	kill -9 "$(cat /tmp/my_process.pid)"
	rm -f /tmp/my_process.pid
	echo "manage_my_process stopped"
elif [ "$1" == "restart" ]; then
	kill -9 "$(cat /tmp/my_process.pid)"
        rm -f /tmp/my_process.pid
	bash manage_my_process &
        echo "$!" > /tmp/my_process.pid
        echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
